# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='like_cheese',
            field=models.BooleanField(default=True),
        ),
    ]
