# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
