# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.datetime_safe.date.today, verbose_name='date_published'),
            preserve_default=False,
        ),
    ]
