# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_persons_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='persons',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
