# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_auto_20160111_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='TaskInitiator',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='actualOwner',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='Dummy', max_length=254),
        ),
    ]
