# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import persons.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_persons_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='thumbnail',
            field=models.FileField(default=0, upload_to=persons.models.get_upload_file_name),
            preserve_default=False,
        ),
    ]
