# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_persons_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='persons.Persons'),
        ),
    ]
