# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0012_auto_20160131_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='LastUpdatedBy',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='LastUpdatedOn',
            field=models.DateField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='persons',
            name='CreatedBy',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='persons',
            name='CreatedOn',
            field=models.DateField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='persons',
            name='LastUpdatedBy',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='persons',
            name='LastUpdatedOn',
            field=models.DateField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='LastUpdatedBy',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='LastUpdatedOn',
            field=models.DateField(max_length=254, null=True),
        ),
    ]
