# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_auto_20160112_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='like',
            field=models.IntegerField(null=True),
        ),
    ]
