# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_comment_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=254, null=True)),
                ('name', models.CharField(max_length=254, null=True)),
                ('description', models.CharField(max_length=254, null=True)),
                ('latitude', models.FloatField(max_length=254, null=True)),
                ('longitude', models.FloatField(max_length=254, null=True)),
                ('CreatedOn', models.DateField(max_length=254, null=True)),
                ('CreatedBy', models.DateField(max_length=254, null=True)),
                ('LastUpdatedOn', models.DateField(max_length=254, null=True)),
                ('LastUpdatedBy', models.DateField(max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='persons',
            name='role',
            field=models.CharField(choices=[('MN', 'Manager'), ('EN', 'Engineer'), ('TE', 'Technician'), ('NA', 'Not Assigned')], default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='site',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='persons.Site'),
        ),
    ]
