# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0013_auto_20160204_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='TaskInitiator',
            new_name='actual_owner',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='TaskPriority',
            new_name='task_initiator',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='TaskStatus',
            new_name='task_priority',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='TaskType',
            new_name='task_status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='actualOwner',
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('H', 'Highest'), ('M', 'Medium'), ('L', 'Low'), ('NA', 'Not Assigned')], default='NA', max_length=10),
        ),
    ]
