# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0014_auto_20160204_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_priority',
            field=models.CharField(choices=[('H', 'Highest'), ('M', 'Medium'), ('L', 'Low'), ('NA', 'Not Assigned')], default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
